title: "Ruyonga Daniel Bosco"
description: "Senior Full Stack Software Engineer | Digital Transformation | AI/ML/LangChain | Elixir/LiveView/Phoenix, Python/Django, Node.js/Express, Vue.js"
logo: /assets/img/profile.jpg # (optional) Add your profile image to /assets/img/
show_downloads: false
google_analytics: # (optional) Your Google Analytics tracking ID
theme: jekyll-theme-minimal

# Social Links
github: ruyonga
linkedin: ruyonga
twitter: ruyonga
stackoverflow: 1706878/ruyonga
facebook: ruyonga.dan